{{- if .Values.storeUI.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.storeUI.name }}-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.storeUI.name }}
  minReplicas: {{ .Values.storeUI.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.storeUI.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.storeUI.autoscaling.targetCPUUtilizationPercentage }}
{{- end }} 