apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.storeUI.name | default "store-ui" }}
spec:
  type: {{ .Values.storeUI.service.type | default "ClusterIP" }}
  selector:
    app: {{ .Values.storeUI.name | default "store-ui" }}
  ports:
  - port: {{ .Values.storeUI.service.port | default 80 }}
    targetPort: {{ .Values.storeUI.service.targetPort | default 3000 }} 