{{- if .Values.ingressController.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-ingress-controller
  labels:
    app: candyhouse-ingress-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-ingress-controller
  labels:
    app: candyhouse-ingress-controller
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-ingress-controller
  labels:
    app: candyhouse-ingress-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-ingress-controller
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-ingress-controller
  namespace: {{ .Release.Namespace }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ingress-controller
  labels:
    app: candyhouse-ingress-controller
spec:
  replicas: {{ .Values.ingressController.replicaCount }}
  selector:
    matchLabels:
      app: candyhouse-ingress-controller
  template:
    metadata:
      labels:
        app: candyhouse-ingress-controller
    spec:
      serviceAccountName: {{ .Release.Name }}-ingress-controller
      containers:
      - name: controller
        image: "{{ .Values.ingressController.image.repository }}:{{ .Values.ingressController.image.tag }}"
        imagePullPolicy: {{ .Values.ingressController.image.pullPolicy }}
        args:
          - /nginx-ingress-controller
          - --configmap=$(POD_NAMESPACE)/{{ .Release.Name }}-ingress-controller
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        ports:
          - containerPort: 80
            name: http
          - containerPort: 443
            name: https
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ingress-controller
  labels:
    app: candyhouse-ingress-controller
spec:
  type: {{ .Values.ingressController.service.type }}
  ports:
  - port: {{ .Values.ingressController.service.port }}
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: candyhouse-ingress-controller
{{- end }}
