{{- if .Values.secrets.kafka.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.kafka.name }}
type: Opaque
stringData:
  url: {{ .Values.global.kafka.url }}
---
{{- end }}

{{- if .Values.secrets.userService.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.userService.name }}
type: Opaque
stringData:
  mongo-uri: {{ .Values.userService.mongoUri | default "mongodb://changeme/user-db" }}
---
{{- end }}

{{- if .Values.secrets.orderService.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.orderService.name }}
type: Opaque
stringData:
  mongo-uri: {{ .Values.orderService.mongoUri | default "mongodb://changeme/order-db" }}
---
{{- end }}

{{- if .Values.secrets.productService.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.productService.name }}
type: Opaque
stringData:
  mongo-uri: {{ .Values.productService.mongoUri | default "mongodb://changeme/product-db" }}
---
{{- end }}

{{- if .Values.secrets.cloudinary.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.cloudinary.name }}
type: Opaque
stringData:
  cloud-name: {{ .Values.productService.cloudinary.cloudName | default "changeme" }}
  api-key: {{ .Values.productService.cloudinary.apiKey | default "changeme" }}
  api-secret: {{ .Values.productService.cloudinary.apiSecret | default "changeme" }}
{{- end }} 