import Head from "next/head";
import { Formik, Form, Field } from "formik";
import {
  Box,
  Button,
  Checkbox,
  Container,
  Divider,
  FormControl,
  FormLabel,
  Heading,
  HStack,
  Input,
  Stack,
  Text,
  useToast,
} from "@chakra-ui/react";

import { api } from "@/utils/api";
import { toFormikValidationSchema } from "zod-formik-adapter";
import { loginInputSchema } from "@/utils/schemas/auth";
import InputControl from "@/components/ui/input-control";
import { NextPageWithLayout } from "../_app";
import BaseLayout from "@/layouts/base-layout";
import Logo from "@/components/shared/logo";
import Link from "next/link";
import { Role } from "@/utils/types/user";
import { useRouter } from "next/router";

const Login: NextPageWithLayout = () => {
  const toast = useToast();
  const router = useRouter();
  const { mutate, isLoading } = api.auth.login.useMutation({
    onSuccess() {
      // alert("logged in");
      
    },
    onError() {
      toast({
        title: "Unable to log you in",
        description: "Please check your credentials",
        status: "error",
        duration: 9000,
        isClosable: true,
        position: "top"
      });
    },
    onSettled(data) {
      if (data) {
        let redirect;

        if (data.role === Role.User) {
          redirect = "/store";
        }
        else {
          redirect = "/vendor/dashboard"
        }

        router.replace(redirect);
      }
    }
  });
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container
          maxW="lg"
          py={{ base: "12", md: "24" }}
          px={{ base: "0", sm: "8" }}
        >
          <Stack spacing="8">
            <Stack spacing="6">
              <Stack spacing={{ base: "2", md: "3" }} textAlign="center">
                <Heading size={{ base: "xs", md: "sm", lg: "xl" }}>
                  Log in to your account
                </Heading>
                <HStack justify="center">
                  <Text color="fg.muted">Do not have an account?</Text>
                  <Link href="/signup">
                    <Button variant="text" size="sm">
                      Sign up
                    </Button>
                  </Link>
                </HStack>
              </Stack>
            </Stack>
            <Box
              py={{ base: "0", sm: "8" }}
              px={{ base: "4", sm: "10" }}
              bg={{ base: "transparent", sm: "bg.surface" }}
              boxShadow={{ base: "none", sm: "md" }}
              borderRadius={{ base: "none", sm: "xl" }}
            >
              <Formik
                initialValues={{
                  email: "",
                  password: "",
                }}
                validationSchema={toFormikValidationSchema(loginInputSchema)}
                onSubmit={(values, actions) => {
                  mutate({
                    ...values,
                  });

                  actions.resetForm();
                }}
              >
                {({ isSubmitting, isValid, dirty }) => (
                  <Form>
                    <InputControl
                      name="email"
                      type="email"
                      label="Email"
                      placeholder="Password"
                    />

                    <InputControl
                      name="password"
                      type="password"
                      label="Password"
                      placeholder="Password"
                    />

                    <Button
                      isDisabled={isSubmitting || !isValid || !dirty}
                      isLoading={isSubmitting}
                      w="full"
                      mt={4}
                      
                      type="submit"
                    >
                      Login
                    </Button>
                  </Form>
                )}
              </Formik>
            </Box>
          </Stack>
        </Container>
      </main>
    </>
  );
};

Login.getLayout = (page) => <BaseLayout>{page}</BaseLayout>;

export default Login;
