import { type NextPage } from "next";
import Head from "next/head";

import { api } from "@/utils/api";
import { List, Heading, ListItem, Text } from "@chakra-ui/react";
import { useAppDispatch, useAppSelector } from "@/store/hooks";
import {
  addCandyToCart,
  clearCart,
  removeCandyFromCart,
} from "@/store/modules/cart";

const Cart: NextPage = () => {
  const dispatch = useAppDispatch();
  const cartItems = useAppSelector((state) => state.cart.items);
  const cartValue = useAppSelector((state) => state.cart.value);
  const cartPrice = useAppSelector((state) => state.cart.price);

  const { mutate: createOrder, isLoading } = api.order.create.useMutation({
    onSuccess() {
      dispatch(clearCart());
      // router.replace("/store");
    },
  });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {cartValue > 0 ? (
          <>
            <Heading>Your cart ({cartValue})</Heading>
            <List spacing={2}>
              {cartItems.map((candy) => (
                <ListItem key={candy._id}>
                  <Text>Name: {candy.name}</Text>
                  <Text>Description: {candy.description}</Text>
                  <Text>Number of items: {candy.itemsInCart}</Text>
                  <Text>Price: {candy.price}</Text>
                </ListItem>
              ))}
            </List>
            <Text>Total: { cartPrice}</Text>
          </>
        ) : (
          <Heading>Your cart is empty</Heading>
        )}
      </main>
    </>
  );
};

export default Cart;
