version: "3.9"

services:
  # proxy:
  #   container_name: proxy
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   restart: "unless-stopped"
  #   networks:
  #     - backend

  order-service:
    container_name: order-service
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
      - /app/node_modules
    restart: 'unless-stopped'
    networks:
      - backend
    env_file:
      - .env.development.local

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
