apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: yashyenugu/user-service:latest
        ports:
        - containerPort: 7000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "7000"
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: user-service-secrets
              key: mongo-uri
        - name: UPSTASH_KAFKA_USERNAME
          valueFrom:
            secretKeyRef:
              name: kafka-secrets
              key: username
        - name: UPSTASH_KAFKA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kafka-secrets
              key: password
        - name: UPSTASH_KAFKA_URL
          valueFrom:
            secretKeyRef:
              name: kafka-secrets
              key: url
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 7000
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 7000
          initialDelaySeconds: 5
          periodSeconds: 10 