version: "3.9"
services:
  app:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    working_dir: /app
    ports:
      - "3000:3000"
    image: candyhouse-dev
    env_file:
      - .env
  
  app-prod:  # Separate service for the production image
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile.prod  # Use Dockerfile.prod for the production image
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb+srv://yashyenugu:6JCupAhMuLbw5Fwc@candyhouse.zufpqrs.mongodb.net/?retryWrites=true&w=majority
      - CLOUDINARY_CLOUD_NAME=yashyenugu
      - CLOUDINARY_API_SECRET=J3LbcC8v9m0LEj-CdHik4sfJKRI
      - CLOUDINARY_API_KEY=239176389364758
      - CLOUDINARY_FOLDER_NAME=candies
      - JWT_SECRET=1ebc2b5018ef57275ff6dccf54468db1d5f57a99087b7d6782d7bd78523a9f1b
      - JWT_EXPIRES_IN=600000
    image: candyhouse  # Give a distinct name to the production image