version: "3.9"
services:
  app:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    working_dir: /app
    ports:
      - "3000:3000"
    image: candyhouse-dev
    env_file:
      - .env
  
  app-prod:  # Separate service for the production image
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile.prod  # Use Dockerfile.prod for the production image
    working_dir: /app
    ports:
      - "3000:3000"
    env_file:
      - .env
    image: candyhouse  # Give a distinct name to the production image