apiVersion: v2
name: candyhouse
description: A Helm chart for the CandyHouse application
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: elasticsearch
    version: 7.17.3
    repository: https://helm.elastic.co
    condition: elasticsearch.enabled
    import-values:
      - child: common
        parent: elasticsearch
  - name: kibana
    version: 7.17.3
    repository: https://helm.elastic.co
    condition: kibana.enabled
  - name: logstash
    version: 7.17.3
    repository: https://helm.elastic.co
    condition: logstash.enabled
  - name: filebeat
    version: 7.17.3
    repository: https://helm.elastic.co
    condition: filebeat.enabled
