export enum USER_RQ {
  LOGGED_IN_USER_QUERY = "LOGGED_IN_USER_QUERY",
}

export enum PRODUCT_RQ {
  PAGINATED_CANDIES = "PAGINATED_CANDIES",
  VENDOR = "VENDOR",
  SIGNED_URL = "SIGNED_URL",
  CANDY = "CANDY",
}

export enum ORDER_RQ {
  BANKS = "BANKS",
  PAGINATED_ORDERS = "PAGINATED_ORDERS",
  ORDER = "ORDER",
}
