{{- if .Values.logstash.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  labels:
    app: logstash
spec:
  replicas: {{ .Values.logstash.replicas }}
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash:{{ .Values.logstash.version }}
        ports:
        - containerPort: 5044
          name: beats
          protocol: TCP
        - containerPort: 9600
          name: http
          protocol: TCP
        env:
        - name: LS_JAVA_OPTS
          value: "-Xms{{ .Values.logstash.javaOpts.xms }} -Xmx{{ .Values.logstash.javaOpts.xmx }}"
        - name: ELASTICSEARCH_HOSTS
          value: "http://elasticsearch-master:9200"
        resources:
          requests:
            cpu: {{ .Values.logstash.resources.requests.cpu }}
            memory: {{ .Values.logstash.resources.requests.memory }}
          limits:
            cpu: {{ .Values.logstash.resources.limits.cpu }}
            memory: {{ .Values.logstash.resources.limits.memory }}
        volumeMounts:
        - name: logstash-config
          mountPath: /usr/share/logstash/config/logstash.yml
          subPath: logstash.yml
        - name: logstash-config
          mountPath: /usr/share/logstash/config/pipeline.yml
          subPath: pipeline.yml
        - name: logstash-config
          mountPath: /usr/share/logstash/pipeline/logstash.conf
          subPath: logstash.conf
        - name: logstash-config
          mountPath: /usr/share/logstash/templates/candyhouse-template.json
          subPath: candyhouse-template.json
        livenessProbe:
          httpGet:
            path: /
            port: 9600
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 9600
          initialDelaySeconds: 30
          periodSeconds: 5
      volumes:
      - name: logstash-config
        configMap:
          name: logstash-config
---
apiVersion: v1
kind: Service
metadata:
  name: logstash
  labels:
    app: logstash
spec:
  type: ClusterIP
  ports:
  - port: 5044
    targetPort: 5044
    name: beats
    protocol: TCP
  - port: 9600
    targetPort: 9600
    name: http
    protocol: TCP
  selector:
    app: logstash
{{- end }}
