apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat
  namespace: {{ .Release.Namespace }}
  labels:
    app: filebeat    
spec:
  selector:
    matchLabels:
      app: filebeat
  template:
    metadata:
      labels:
        app: filebeat
    spec:
      serviceAccountName: filebeat
      terminationGracePeriodSeconds: 30
      containers:
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:7.10.0
        args:
          - "-c"
          - "/etc/filebeat.yml"
          - "-e"
        volumeMounts:
          - name: config
            mountPath: /etc/filebeat.yml
            subPath: filebeat.yml
          - name: varlog
            mountPath: /var/log
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
            readOnly: true
      volumes:
        - name: config
          configMap:
            name: filebeat-config
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: filebeat
data:
  filebeat.yml: |
    filebeat.autodiscover:
      providers:
        - type: kubernetes
          hints.enabled: true
    filebeat.inputs:
      - type: container
        scan_symlinks: true
        paths:
          - /var/log/containers/*.log
    # TODO: Temporarily disable Kubernetes metadata processor until matcher settings are resolved
    # processors:
    #   - add_kubernetes_metadata:
    #       in_cluster: true
    output.logstash:
      hosts: ["logstash:5044"] 