apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.userService.name }}
spec:
  type: {{ .Values.userService.service.type }}
  selector:
    app: {{ .Values.userService.name }}
  ports:
  - port: {{ .Values.userService.service.port }}
    targetPort: {{ .Values.userService.service.targetPort }} 