name: Build and publish product-service image

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./product-service
          push: true
          tags: yashyenugu/product-service:latest

  run-tests:
    runs-on: ubuntu-latest
    env:
      PORT: 4000
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      LOG_FORMAT: combined
      LOG_DIR: ../logs
      ORIGIN: your.domain.com
      CREDENTIALS: true
      MONGO_URI: ${{ secrets.PRODUCT_MONGO_URI }}
      MONGO_TEST_URI: ${{ secrets.MONGO_TEST_URI }}
      CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
      CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
      CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
      CLOUDINARY_FOLDER_NAME: ${{ secrets.CLOUDINARY_FOLDER_NAME }}
      UPSTASH_KAFKA_USERNAME: ${{ secrets.UPSTASH_KAFKA_USERNAME }}
      UPSTASH_KAFKA_PASSWORD: ${{ secrets.UPSTASH_KAFKA_PASSWORD }}
      UPSTASH_KAFKA_URL: ${{ secrets.UPSTASH_KAFKA_URL }}
      runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Change Directory
        run: cd product-service

      # - name: Build Containers
      #   run: docker-compose build

      - name: Run Tests and Coverage
        run: docker-compose -f docker-compose.yml up
